#!/bin/sh

# Script to get anime game's wish history link for paimon.moe


if [ $XDG_SESSION_TYPE = "wayland" ]; then
    if cat -v "$HOME/.local/share/anime-game-launcher/game/drive_c/Program Files/Genshin Impact/GenshinImpact_Data/webCaches/Cache/Cache_Data/data_2" | grep "e20190909gacha-v2" | sed 's/1\/0\//\n/g' | grep "e20190909gacha-v2" | sed 's/global.*/global/' | tail -n 1 | wl-copy -n ; then
        quick-notify "Copied wish link"
    else
        quick-notify "Failed to copy"
    fi
else
    if cat -v "$HOME/.local/share/anime-game-launcher/game/drive_c/Program Files/Genshin Impact/GenshinImpact_Data/webCaches/Cache/Cache_Data/data_2" | grep "e20190909gacha-v2" | sed 's/1\/0\//\n/g' | grep "e20190909gacha-v2" | sed 's/global.*/global/' | tail -n 1 | xclip -sel c ; then
        quick-notify "Copied wish link"
    else
        quick-notify "Failed to copy"
    fi
fi
