#!/bin/bash

tasks=$(task status:pending -notified due export | jq -r '.[].description')
[ -z "$tasks" ] && exit 0
for task in $tasks; do
  notify-send 'A task is due.' "$task"
done
task rc.bulk=0 rc.confirmation=off status:pending -notified due modify +notified
